### ISSUE TITLE
Steam valid authentication returns to /signin-steam with parameters, and throws "Error 500" Without any information in Console.

### ISSUE THREAD

**Issue by kamilk91** [aspnet-contrib/AspNet.Security.OpenId.Providers#79]
**Describe the bug**
Sometimes (not always!!) after correct login by steam, when returning to ```signin-steam``` Error 500 is throwed. 

**Steps To reproduce**
Just login by steam, with parameters: 

```
<form method='post' action='/signin' name='steamAuth'>
                <input type='hidden' name='Provider' value='Steam'>
                <input type='hidden' name='ReturnUrl' value='"http://127.0.0.1/"'>
```

**Expected behaviour**
Correct login, and claim claims. 

**System information:**
 - OS: Windows 10, and Ubuntu (2 different builds)
 - Library Version: latest
 - .NET Core 3.0

**Comment by martincostello** [comment]
Can you please provide error logs for the 500s? Otherwise there's not much to go on to help.

**Comment by kamilk91** [comment]
@martincostello I can't see any Logs... I don't know why, is your library logging errors? 
BTW i saw that its 500 always when i see this confirmation screen:

![image](https://user-images.githubusercontent.com/26136300/77755098-d86b3d00-702c-11ea-8083-ba66b333fae4.png)

**Comment by kamilk91** [comment]
@martincostello  okay i have logs. It looks like some antiforgery problem, bout shouldn't it default throws 401 error? 

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

Request starting HTTP/1.1 GET http://localhost.pl:50000/signin-steam?state=CfDJ8HbqQfhQ7aZKt8GCIpM9OMjfmcardDJLv3W9vpsweRxfg8FSe2j888_pWRTGDBvr6InIWR1Huvp2PErAPt8iG60-FjIG4nzffkrWyHXePrD6T3KOFRej12_mmlWQkjqkfKNWkLP1JBFFYv5gCaHIvrJhfuLM5lKdf-QXItW0nrFucWhhcX2hy1EvEFwpJPmhJwV7uq_db55EcLnzAnyZbM55Nb9_ixdCzI01FUy2ByxDmyZ92fol2H57coRHrBjAUoiJSY_nwullb-2UD7WDIXwwaW7Hu6IEXvx2l35ZoMiq&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198120154806&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198120154806&openid.return_to=http%3A%2F%2Flocalhost.pl%3A50000%2Fsignin-steam%3Fstate%3DCfDJ8HbqQfhQ7aZKt8GCIpM9OMjfmcardDJLv3W9vpsweRxfg8FSe2j888_pWRTGDBvr6InIWR1Huvp2PErAPt8iG60-FjIG4nzffkrWyHXePrD6T3KOFRej12_mmlWQkjqkfKNWkLP1JBFFYv5gCaHIvrJhfuLM5lKdf-QXItW0nrFucWhhcX2hy1EvEFwpJPmhJwV7uq_db55EcLnzAnyZbM55Nb9_ixdCzI01FUy2ByxDmyZ92fol2H57coRHrBjAUoiJSY_nwullb-2UD7WDIXwwaW7Hu6IEXvx2l35ZoMiq&openid.response_nonce=2020-03-27T12%3A32%3A38ZKRZvcJ98MWD9dIL1soVv0mjvsBI%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=eHczmOt9clwHCcmxTefKfTDWk7A%3D
           warn: AspNet.Security.OpenId.Steam.SteamAuthenticationHandler[15]
                                        '.AspNetCore.Correlation.Steam.vkHFVBan4Z4ToVlIpR9usDFOKw-uUlOOfgMPVE2jDg8' cookie not found.
info: AspNet.Security.OpenId.Steam.SteamAuthenticationHandler[4]
                                         Error from RemoteAuthentication: The authentication response was rejected because the anti-forgery token was invalid..
                   fail: Microsoft.AspNetCore.Server.Kestrel[13]

    Connection id "0HLUI9BMQ1S7D", Request id "0HLUI9BMQ1S7D:00000004": An unhandled exception was thrown by the application.
                System.Exception: An error was encountered while handling the remote login.
                         ---> System.Exception: The authentication response was rejected because the anti-forgery token was invalid.
                                      --- End of inner exception stack trace ---

 at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
        at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
            info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

Request finished in 6.321000000000001ms 500 

```

**Comment by martincostello** [comment]
My guess would be that you have Same Site issues with the OpenID connect cookie. It's probably being removed and then authentication will fail as it can't check the antiforgery token.

There's more information about it here: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

If it's the case, then this is something you need to fix on your end and isn't a bug in this library.

**Comment by kamilk91** [comment]
@martincostello fixed with your link. Thank you very much, ill never find that issue alone.
